# Change these first
owner: devramsean0 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portfolio
    url: https://www.sean.cyou

status-website:
  cname: status.sean.cyou
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page for the public services that I host
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
